// <auto-generated />
namespace KariyerEntity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _28122021003 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_28122021003));
        
        string IMigrationMetadata.Id
        {
            get { return "202112282027375_28122021003"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
